# Generated by Django 3.2.9 on 2021-11-27 18:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='名称')),
                ('remarks', models.CharField(default='', max_length=2048, verbose_name='描述')),
                ('git_ssh_url', models.CharField(default='', max_length=4096, verbose_name='ssh地址')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(default=None, null=True, verbose_name='更新时间')),
                ('update_msg', models.CharField(default='', max_length=4096, verbose_name='更新消息')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='仓库所有者')),
            ],
            options={
                'db_table': 't_repository',
            },
        ),
        migrations.CreateModel(
            name='SharedRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='名称')),
                ('remarks', models.CharField(default='', max_length=2048, verbose_name='描述')),
                ('branch', models.CharField(default='', max_length=512, verbose_name='分支名称')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(default=None, null=True, verbose_name='更新时间')),
                ('update_msg', models.CharField(default='', max_length=4096, verbose_name='更新消息')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='app_repo.repository', verbose_name='原仓库')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='共享仓库所有者')),
            ],
            options={
                'db_table': 't_shared_repo',
            },
        ),
        migrations.CreateModel(
            name='SharedRepoStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
                ('shared_repo', models.ForeignKey(db_column='shared_repo_id', on_delete=django.db.models.deletion.CASCADE, to='app_repo.sharedrepo', verbose_name='共享仓库')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 't_shared_repo_star',
            },
        ),
        migrations.CreateModel(
            name='SharedRepoAccessCtrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='授权过期时间')),
                ('shared_repo', models.ForeignKey(db_column='shared_repo_id', on_delete=django.db.models.deletion.CASCADE, to='app_repo.sharedrepo', verbose_name='共享仓库')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 't_shared_repo_access_ctrl',
            },
        ),
    ]
